import type {NextPage} from 'next'
import Head from 'next/head'
import Image from 'next/image'
import apes from '../apes.json'

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <h1 className={"text-2xl font-extrabold p-3 text-white bg-black"}>Average Ape</h1>

            <main className={'container mx-auto'}>
                {
                    Object.keys(apes).map((k) => (
                        <div key={k} className={'my-3'}>
                            <div className={'flex items-center justify-items-center'}>
                                <h2 className={'text-xl font-extrabold text-white bg-black px-3 py-2'}>{k}</h2>
                            </div>
                            <div className={'grid grid-cols-2 md:grid-cols-4 lg:grid-cols-6 xl:grid-cols-8 gap-0 my-3'}>
                                {
                                    Object.keys(apes[k]).map((v) => (
                                        <div key={v} className={'flex flex-col justify-items-center items-center'}>
                                            <div
                                                className={'w-44 h-44 bg-gray-200 border shadow-inner border-gray-500 hover:border-purple-500 hover:bg-purple-200 rounded-lg'}>
                                                <Image src={`/apes/${apes[k][v].filename}.png`}
                                                       width={'200px'}
                                                       height={'200px'}/>
                                            </div>
                                            <h3 className={'text-center text-sm text-gray-500 mt-1 mb-3'}>{v}</h3>
                                        </div>
                                    ))
                                }
                            </div>
                        </div>
                    ))
                }
                {/*<pre>{JSON.stringify(Object.entries(apes), null, 2)}</pre>*/}
                {/*<pre>{JSON.stringify(apes, null, 2)}</pre>*/}
            </main>

        </div>
    )
}

export default Home
